spring:
  application:
    name: currency-conversion-service
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8100

forex-service:
  ribbon:
    listOfServers: http://localhost:8000
